[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Force HTTPS
[[redirects]]
  from = "http://transformationmadeeasy.me/*"
  to = "https://transformationmadeeasy.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.transformationmadeeasy.me/*"
  to = "https://transformationmadeeasy.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.transformationmadeeasy.me/*"
  to = "https://transformationmadeeasy.me/:splat"
  status = 301
  force = true

# SPA fallback - only for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {method = ["GET"]}

# XML content type headers
[[headers]]
  for = "/sitemap-index.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sitemap-*.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
